-- apply changes
create table url_check (
  id                            bigint generated by default as identity not null,
  status_code                   integer not null,
  title                         varchar(255),
  h1                            varchar(255),
  description                   clob,
  url_id                        bigint,
  created_at                    timestamp not null,
  constraint pk_url_check primary key (id)
);

create index ix_url_check_url_name on url_check (url_name);
alter table url_check add constraint fk_url_check_url_name foreign key (url_name) references url (id) on delete restrict on update restrict;

