datasource:
  default: ${APP_ENV}
  development:
    username: myuser
    password: mypass
    url: jdbc:postgresql://localhost:5432/mydb
  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

ebean:
  ddl:
    run: true
    generate: true
    seedSql: seed.sql
  migration:
    run: true

